# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/panyue/code/my_github/HUST-OperatingSystem-Labs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/panyue/code/my_github/HUST-OperatingSystem-Labs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/panyue/code/my_github/HUST-OperatingSystem-Labs/CMakeFiles /home/panyue/code/my_github/HUST-OperatingSystem-Labs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/panyue/code/my_github/HUST-OperatingSystem-Labs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pipe

# Build rule for target.
pipe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pipe
.PHONY : pipe

# fast build rule for target.
pipe/fast:
	$(MAKE) -f CMakeFiles/pipe.dir/build.make CMakeFiles/pipe.dir/build
.PHONY : pipe/fast

#=============================================================================
# Target rules for targets named fifo

# Build rule for target.
fifo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fifo
.PHONY : fifo

# fast build rule for target.
fifo/fast:
	$(MAKE) -f CMakeFiles/fifo.dir/build.make CMakeFiles/fifo.dir/build
.PHONY : fifo/fast

#=============================================================================
# Target rules for targets named zxcpyp_lib

# Build rule for target.
zxcpyp_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zxcpyp_lib
.PHONY : zxcpyp_lib

# fast build rule for target.
zxcpyp_lib/fast:
	$(MAKE) -f zxcpyplib/CMakeFiles/zxcpyp_lib.dir/build.make zxcpyplib/CMakeFiles/zxcpyp_lib.dir/build
.PHONY : zxcpyp_lib/fast

lab01-Pipe/fifo.o: lab01-Pipe/fifo.c.o

.PHONY : lab01-Pipe/fifo.o

# target to build an object file
lab01-Pipe/fifo.c.o:
	$(MAKE) -f CMakeFiles/fifo.dir/build.make CMakeFiles/fifo.dir/lab01-Pipe/fifo.c.o
.PHONY : lab01-Pipe/fifo.c.o

lab01-Pipe/fifo.i: lab01-Pipe/fifo.c.i

.PHONY : lab01-Pipe/fifo.i

# target to preprocess a source file
lab01-Pipe/fifo.c.i:
	$(MAKE) -f CMakeFiles/fifo.dir/build.make CMakeFiles/fifo.dir/lab01-Pipe/fifo.c.i
.PHONY : lab01-Pipe/fifo.c.i

lab01-Pipe/fifo.s: lab01-Pipe/fifo.c.s

.PHONY : lab01-Pipe/fifo.s

# target to generate assembly for a file
lab01-Pipe/fifo.c.s:
	$(MAKE) -f CMakeFiles/fifo.dir/build.make CMakeFiles/fifo.dir/lab01-Pipe/fifo.c.s
.PHONY : lab01-Pipe/fifo.c.s

lab01-Pipe/pipe.o: lab01-Pipe/pipe.c.o

.PHONY : lab01-Pipe/pipe.o

# target to build an object file
lab01-Pipe/pipe.c.o:
	$(MAKE) -f CMakeFiles/pipe.dir/build.make CMakeFiles/pipe.dir/lab01-Pipe/pipe.c.o
.PHONY : lab01-Pipe/pipe.c.o

lab01-Pipe/pipe.i: lab01-Pipe/pipe.c.i

.PHONY : lab01-Pipe/pipe.i

# target to preprocess a source file
lab01-Pipe/pipe.c.i:
	$(MAKE) -f CMakeFiles/pipe.dir/build.make CMakeFiles/pipe.dir/lab01-Pipe/pipe.c.i
.PHONY : lab01-Pipe/pipe.c.i

lab01-Pipe/pipe.s: lab01-Pipe/pipe.c.s

.PHONY : lab01-Pipe/pipe.s

# target to generate assembly for a file
lab01-Pipe/pipe.c.s:
	$(MAKE) -f CMakeFiles/pipe.dir/build.make CMakeFiles/pipe.dir/lab01-Pipe/pipe.c.s
.PHONY : lab01-Pipe/pipe.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... pipe"
	@echo "... fifo"
	@echo "... zxcpyp_lib"
	@echo "... lab01-Pipe/fifo.o"
	@echo "... lab01-Pipe/fifo.i"
	@echo "... lab01-Pipe/fifo.s"
	@echo "... lab01-Pipe/pipe.o"
	@echo "... lab01-Pipe/pipe.i"
	@echo "... lab01-Pipe/pipe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

